import Head from "next/head";
// import Image from "next/image";
import { Inter } from "next/font/google";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
// import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [user, setUser] = useState(null);
  const router = useRouter();

  useEffect(() => {
    // Check if user data is present in localStorage
    const userData = JSON.parse(localStorage.getItem("userData"));
    if (userData) {
      setUser(userData);
    }
  }, []);

  const handleDashboardRedirect = () => {
    if (user?.userType === "market") {
      router.push("/dashboard/market");
    } else if (user?.userType === "agent") {
      router.push("/dashboard/agent");
    }
  };
  return (
    <>
      <Head>
        <title>TAILORMADE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`container-md ${inter.className}`}>
        <div className="d-flex justify-content-center align-items-center vh-100">
          <div className="text-center">
            <h1>Welcome to TAILORMADE</h1>
            {user ? (
              <button
                type="button"
                className="btn btn-primary m-2"
                onClick={handleDashboardRedirect}
              >
                Dashboard
              </button>
            ) : (
              <>
                <button type="button" className="btn btn-primary m-2">
                  <a href="/login">Login</a>
                </button>
                <button type="button" className="btn btn-secondary m-2">
                  <a href="/signup">Sign Up</a>
                </button>
              </>
            )}
          </div>
        </div>
      </main>
    </>
  );
}
